/******************************************************************************
 *
 * Module: ICU
 *
 * File Name: Ultrasonic.c
 *
 * Description: source file for the Ultrasonic driver
 *
 * Author: Yousif
 *
 *******************************************************************************/

#include "std_types.h"
#include "gpio.h"
#include "icu.h"
#include "util/delay.h"
#include "Ultrasonic.h"
/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

uint8 timer_counter=0; // global variable for timer counter that increments at interrupts
uint32 timer_value;  //global variable for time of pulse
uint8 sensor_work=0; // global variable to detect starting of calculate distance
/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/
 /* Description
 This is the call back function called by the ICU driver.
 This is used to calculate the high time (pulse time) generated by the ultrasonic sensor*/

void Ultrasonic_edgeProcessing(void);
/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/
/*
 * Description
 *Initialize the ICU driver as required.
 *Setup the ICU call back function.
 *Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	Icu_ConfigType Icu_config={F_CPU_8,RISING};
	Icu_init(&Icu_config); /*initialize Icu unit8*/
	/*setup call back*/
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, PIN_OUTPUT);/*setup trigger */
	GPIO_setupPinDirection(ULTRASONIC_ECHO_PORT, ULTRASONIC_ECHO_PIN, PIN_INPUT);/*setup echo */
}

/*
 * Description: Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void)
{
GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_HIGH);
_delay_us(10);
GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_LOW);
}

/*
 Description
 Send the trigger pulse by using Ultrasonic_Trigger function.
 Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void)
{
Ultrasonic_Trigger();
sensor_work=1;
return (uint16)timer_value;
}
void Ultrasonic_edgeProcessing(void)
{
	if(sensor_work)
	{
	timer_counter++;
	if(timer_counter==1)
	{
		/*
				 * Clear the timer counter register to start measurements from the
				 * first detected rising edge
				 */
				Icu_clearTimerValue();
				/* Detect falling edge */
				Icu_setEdgeDetectionType(FALLING);
	}
	else if(timer_counter==2)
	{
		/* get value of ICR register that contains pulse time*/
		timer_value=Icu_getInputCaptureValue();
		/* Detect rising edge*/
		Icu_setEdgeDetectionType(RISING);
		timer_counter=0;
	}
	}

}
